services:
  - type: web
    name: my-react-app
    env: node
    plan: free
    buildCommand: "npm install && npm run build"  # Install and build React app
    startCommand: "npm run serve"  # Serving the build folder
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: "https://hidebehider-backend.onrender.com"  # Your backend API URL
