services:
  - type: web
    name: hidebehider-frontend
    env: node
    plan: free
    buildCommand: "npm install --include=dev && npm run build"   # Ensure 'vite' is installed and build the project
    startCommand: "npm run preview -- --port 10000" # This runs the start command from package.json
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: "https://hidebehider-backend.onrender.com"  # Add any necessary environment variables
